#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 61
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 31
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_CR = 1,
  anon_sym_LF = 2,
  aux_sym_comment_token1 = 3,
  anon_sym_SLASH_STAR = 4,
  aux_sym_comment_token2 = 5,
  anon_sym_STAR_SLASH = 6,
  anon_sym_SEMI = 7,
  anon_sym_LBRACE = 8,
  anon_sym_RBRACE = 9,
  anon_sym_scope = 10,
  anon_sym_LPAREN = 11,
  anon_sym_COMMA = 12,
  anon_sym_RPAREN = 13,
  sym__decimal_literal = 14,
  sym_name = 15,
  sym_type_name = 16,
  sym_source_file = 17,
  aux_sym__newline = 18,
  sym_comment = 19,
  sym__statements = 20,
  sym__statement_line = 21,
  sym__statement = 22,
  sym_block = 23,
  sym__expression = 24,
  sym_function_call = 25,
  sym__numeric_literal = 26,
  aux_sym_comment_repeat1 = 27,
  aux_sym__statements_repeat1 = 28,
  aux_sym__statement_line_repeat1 = 29,
  aux_sym_function_call_repeat1 = 30,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_CR] = "\r",
  [anon_sym_LF] = "\n",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_SLASH_STAR] = "/*",
  [aux_sym_comment_token2] = "comment_token2",
  [anon_sym_STAR_SLASH] = "*/",
  [anon_sym_SEMI] = ";",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_scope] = "scope",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [sym__decimal_literal] = "_decimal_literal",
  [sym_name] = "name",
  [sym_type_name] = "type_name",
  [sym_source_file] = "source_file",
  [aux_sym__newline] = "_newline",
  [sym_comment] = "comment",
  [sym__statements] = "_statements",
  [sym__statement_line] = "_statement_line",
  [sym__statement] = "_statement",
  [sym_block] = "block",
  [sym__expression] = "_expression",
  [sym_function_call] = "function_call",
  [sym__numeric_literal] = "_numeric_literal",
  [aux_sym_comment_repeat1] = "comment_repeat1",
  [aux_sym__statements_repeat1] = "_statements_repeat1",
  [aux_sym__statement_line_repeat1] = "_statement_line_repeat1",
  [aux_sym_function_call_repeat1] = "function_call_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_CR] = anon_sym_CR,
  [anon_sym_LF] = anon_sym_LF,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [anon_sym_STAR_SLASH] = anon_sym_STAR_SLASH,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_scope] = anon_sym_scope,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym__decimal_literal] = sym__decimal_literal,
  [sym_name] = sym_name,
  [sym_type_name] = sym_type_name,
  [sym_source_file] = sym_source_file,
  [aux_sym__newline] = aux_sym__newline,
  [sym_comment] = sym_comment,
  [sym__statements] = sym__statements,
  [sym__statement_line] = sym__statement_line,
  [sym__statement] = sym__statement,
  [sym_block] = sym_block,
  [sym__expression] = sym__expression,
  [sym_function_call] = sym_function_call,
  [sym__numeric_literal] = sym__numeric_literal,
  [aux_sym_comment_repeat1] = aux_sym_comment_repeat1,
  [aux_sym__statements_repeat1] = aux_sym__statements_repeat1,
  [aux_sym__statement_line_repeat1] = aux_sym__statement_line_repeat1,
  [aux_sym_function_call_repeat1] = aux_sym_function_call_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_CR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_STAR_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_scope] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym__decimal_literal] = {
    .visible = false,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_type_name] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__newline] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__statements] = {
    .visible = false,
    .named = true,
  },
  [sym__statement_line] = {
    .visible = false,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym__numeric_literal] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__statements_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__statement_line_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_call_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead == '\r') ADVANCE(10);
      if (lookahead == '#') ADVANCE(12);
      if (lookahead == '(') ADVANCE(23);
      if (lookahead == ')') ADVANCE(25);
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '.') ADVANCE(6);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == ';') ADVANCE(19);
      if (lookahead == '_') ADVANCE(33);
      if (lookahead == 's') ADVANCE(29);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead == '}') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(35);
      END_STATE();
    case 1:
      if (lookahead == '#') ADVANCE(12);
      if (lookahead == '*') ADVANCE(17);
      if (lookahead == '/') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(14);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(13);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(18);
      END_STATE();
    case 5:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead == '\r') ADVANCE(10);
      if (lookahead == '#') ADVANCE(12);
      if (lookahead == ')') ADVANCE(25);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '.') ADVANCE(6);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead == '}') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(8)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_CR);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '#') ADVANCE(12);
      if (lookahead == '*') ADVANCE(17);
      if (lookahead == '/') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(14);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '*') ADVANCE(13);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '/') ADVANCE(18);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_STAR_SLASH);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_scope);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym__decimal_literal);
      if (lookahead == '.') ADVANCE(6);
      if (lookahead == '_') ADVANCE(5);
      if (lookahead == 'e') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym__decimal_literal);
      if (lookahead == '_') ADVANCE(6);
      if (lookahead == 'e') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym__decimal_literal);
      if (lookahead == '_') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'c') ADVANCE(31);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'e') ADVANCE(22);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'o') ADVANCE(32);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'p') ADVANCE(30);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_name);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(35);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_type_name);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 8},
  [2] = {.lex_state = 8},
  [3] = {.lex_state = 8},
  [4] = {.lex_state = 8},
  [5] = {.lex_state = 8},
  [6] = {.lex_state = 8},
  [7] = {.lex_state = 8},
  [8] = {.lex_state = 8},
  [9] = {.lex_state = 8},
  [10] = {.lex_state = 8},
  [11] = {.lex_state = 8},
  [12] = {.lex_state = 8},
  [13] = {.lex_state = 8},
  [14] = {.lex_state = 8},
  [15] = {.lex_state = 8},
  [16] = {.lex_state = 8},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 8},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 8},
  [24] = {.lex_state = 8},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 8},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {(TSStateId)(-1)},
  [59] = {(TSStateId)(-1)},
  [60] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_CR] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_STAR_SLASH] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_scope] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym__decimal_literal] = ACTIONS(1),
    [sym_name] = ACTIONS(1),
    [sym_type_name] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(52),
    [aux_sym__newline] = STATE(4),
    [sym_comment] = STATE(1),
    [sym__statements] = STATE(56),
    [sym__statement_line] = STATE(30),
    [sym__statement] = STATE(41),
    [sym_block] = STATE(27),
    [sym__expression] = STATE(51),
    [sym_function_call] = STATE(37),
    [sym__numeric_literal] = STATE(39),
    [aux_sym__statement_line_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(7),
    [anon_sym_CR] = ACTIONS(9),
    [anon_sym_LF] = ACTIONS(11),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(13),
    [sym__decimal_literal] = ACTIONS(15),
    [sym_name] = ACTIONS(17),
  },
  [2] = {
    [aux_sym__newline] = STATE(6),
    [sym_comment] = STATE(2),
    [sym__statements] = STATE(54),
    [sym__statement_line] = STATE(30),
    [sym__statement] = STATE(41),
    [sym_block] = STATE(27),
    [sym__expression] = STATE(51),
    [sym_function_call] = STATE(37),
    [sym__numeric_literal] = STATE(39),
    [aux_sym__statement_line_repeat1] = STATE(7),
    [anon_sym_CR] = ACTIONS(9),
    [anon_sym_LF] = ACTIONS(11),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(19),
    [sym__decimal_literal] = ACTIONS(15),
    [sym_name] = ACTIONS(17),
  },
  [3] = {
    [aux_sym__newline] = STATE(9),
    [sym_comment] = STATE(3),
    [sym__statement_line] = STATE(40),
    [sym__statement] = STATE(41),
    [sym_block] = STATE(27),
    [sym__expression] = STATE(51),
    [sym_function_call] = STATE(37),
    [sym__numeric_literal] = STATE(39),
    [aux_sym__statement_line_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_CR] = ACTIONS(9),
    [anon_sym_LF] = ACTIONS(11),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(21),
    [sym__decimal_literal] = ACTIONS(15),
    [sym_name] = ACTIONS(17),
  },
  [4] = {
    [aux_sym__newline] = STATE(9),
    [sym_comment] = STATE(4),
    [sym__statements] = STATE(53),
    [sym__statement_line] = STATE(30),
    [sym__statement] = STATE(41),
    [sym_block] = STATE(27),
    [sym__expression] = STATE(51),
    [sym_function_call] = STATE(37),
    [sym__numeric_literal] = STATE(39),
    [aux_sym__statement_line_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(23),
    [anon_sym_CR] = ACTIONS(9),
    [anon_sym_LF] = ACTIONS(11),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(13),
    [sym__decimal_literal] = ACTIONS(15),
    [sym_name] = ACTIONS(17),
  },
  [5] = {
    [aux_sym__newline] = STATE(9),
    [sym_comment] = STATE(5),
    [sym__statement_line] = STATE(40),
    [sym__statement] = STATE(41),
    [sym_block] = STATE(27),
    [sym__expression] = STATE(51),
    [sym_function_call] = STATE(37),
    [sym__numeric_literal] = STATE(39),
    [aux_sym__statement_line_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(25),
    [anon_sym_CR] = ACTIONS(9),
    [anon_sym_LF] = ACTIONS(11),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(25),
    [sym__decimal_literal] = ACTIONS(15),
    [sym_name] = ACTIONS(17),
  },
  [6] = {
    [aux_sym__newline] = STATE(9),
    [sym_comment] = STATE(6),
    [sym__statements] = STATE(57),
    [sym__statement_line] = STATE(30),
    [sym__statement] = STATE(41),
    [sym_block] = STATE(27),
    [sym__expression] = STATE(51),
    [sym_function_call] = STATE(37),
    [sym__numeric_literal] = STATE(39),
    [aux_sym__statement_line_repeat1] = STATE(7),
    [anon_sym_CR] = ACTIONS(9),
    [anon_sym_LF] = ACTIONS(11),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(27),
    [sym__decimal_literal] = ACTIONS(15),
    [sym_name] = ACTIONS(17),
  },
  [7] = {
    [sym_comment] = STATE(7),
    [sym__statement] = STATE(42),
    [sym_block] = STATE(27),
    [sym__expression] = STATE(51),
    [sym_function_call] = STATE(37),
    [sym__numeric_literal] = STATE(39),
    [aux_sym__statement_line_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(29),
    [anon_sym_CR] = ACTIONS(29),
    [anon_sym_LF] = ACTIONS(29),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(29),
    [sym__decimal_literal] = ACTIONS(15),
    [sym_name] = ACTIONS(17),
  },
  [8] = {
    [aux_sym__newline] = STATE(9),
    [sym_comment] = STATE(8),
    [sym__statement_line] = STATE(40),
    [sym__statement] = STATE(41),
    [sym_block] = STATE(27),
    [sym__expression] = STATE(51),
    [sym_function_call] = STATE(37),
    [sym__numeric_literal] = STATE(39),
    [aux_sym__statement_line_repeat1] = STATE(7),
    [anon_sym_CR] = ACTIONS(9),
    [anon_sym_LF] = ACTIONS(11),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(13),
    [sym__decimal_literal] = ACTIONS(15),
    [sym_name] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(33), 1,
      anon_sym_CR,
    ACTIONS(36), 1,
      anon_sym_LF,
    STATE(9), 2,
      aux_sym__newline,
      sym_comment,
    ACTIONS(31), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym__decimal_literal,
      sym_name,
  [26] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(10), 1,
      sym_comment,
    ACTIONS(39), 9,
      ts_builtin_sym_end,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym__decimal_literal,
      sym_name,
  [47] = 11,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_CR,
    ACTIONS(11), 1,
      anon_sym_LF,
    ACTIONS(15), 1,
      sym__decimal_literal,
    ACTIONS(17), 1,
      sym_name,
    ACTIONS(41), 1,
      anon_sym_RPAREN,
    STATE(9), 1,
      aux_sym__newline,
    STATE(11), 1,
      sym_comment,
    STATE(22), 1,
      sym__expression,
    STATE(39), 2,
      sym_function_call,
      sym__numeric_literal,
  [82] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(45), 1,
      anon_sym_LBRACE,
    STATE(27), 1,
      sym_block,
    STATE(12), 2,
      sym_comment,
      aux_sym__statement_line_repeat1,
    ACTIONS(43), 6,
      ts_builtin_sym_end,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_RBRACE,
      sym__decimal_literal,
      sym_name,
  [107] = 11,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_CR,
    ACTIONS(11), 1,
      anon_sym_LF,
    ACTIONS(15), 1,
      sym__decimal_literal,
    ACTIONS(17), 1,
      sym_name,
    ACTIONS(48), 1,
      anon_sym_RPAREN,
    STATE(11), 1,
      aux_sym__newline,
    STATE(13), 1,
      sym_comment,
    STATE(25), 1,
      sym__expression,
    STATE(39), 2,
      sym_function_call,
      sym__numeric_literal,
  [142] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(14), 1,
      sym_comment,
    ACTIONS(31), 9,
      ts_builtin_sym_end,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym__decimal_literal,
      sym_name,
  [163] = 10,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_CR,
    ACTIONS(11), 1,
      anon_sym_LF,
    ACTIONS(15), 1,
      sym__decimal_literal,
    ACTIONS(17), 1,
      sym_name,
    STATE(9), 1,
      aux_sym__newline,
    STATE(15), 1,
      sym_comment,
    STATE(31), 1,
      sym__expression,
    STATE(39), 2,
      sym_function_call,
      sym__numeric_literal,
  [195] = 10,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_CR,
    ACTIONS(11), 1,
      anon_sym_LF,
    ACTIONS(15), 1,
      sym__decimal_literal,
    ACTIONS(17), 1,
      sym_name,
    STATE(15), 1,
      aux_sym__newline,
    STATE(16), 1,
      sym_comment,
    STATE(32), 1,
      sym__expression,
    STATE(39), 2,
      sym_function_call,
      sym__numeric_literal,
  [227] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(17), 1,
      sym_comment,
    ACTIONS(50), 7,
      ts_builtin_sym_end,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [246] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(18), 1,
      sym_comment,
    ACTIONS(52), 7,
      ts_builtin_sym_end,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym__decimal_literal,
      sym_name,
  [265] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(19), 1,
      sym_comment,
    ACTIONS(54), 7,
      ts_builtin_sym_end,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [284] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(20), 1,
      sym_comment,
    ACTIONS(56), 7,
      ts_builtin_sym_end,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [303] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(21), 1,
      sym_comment,
    ACTIONS(58), 7,
      ts_builtin_sym_end,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [322] = 10,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_CR,
    ACTIONS(11), 1,
      anon_sym_LF,
    ACTIONS(60), 1,
      anon_sym_LPAREN,
    ACTIONS(62), 1,
      anon_sym_COMMA,
    ACTIONS(64), 1,
      anon_sym_RPAREN,
    STATE(22), 1,
      sym_comment,
    STATE(33), 1,
      aux_sym__newline,
    STATE(45), 1,
      aux_sym_function_call_repeat1,
  [353] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(23), 1,
      sym_comment,
    ACTIONS(66), 7,
      ts_builtin_sym_end,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym__decimal_literal,
      sym_name,
  [372] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(24), 1,
      sym_comment,
    ACTIONS(68), 7,
      ts_builtin_sym_end,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym__decimal_literal,
      sym_name,
  [391] = 10,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_CR,
    ACTIONS(11), 1,
      anon_sym_LF,
    ACTIONS(41), 1,
      anon_sym_RPAREN,
    ACTIONS(60), 1,
      anon_sym_LPAREN,
    ACTIONS(62), 1,
      anon_sym_COMMA,
    STATE(25), 1,
      sym_comment,
    STATE(34), 1,
      aux_sym__newline,
    STATE(44), 1,
      aux_sym_function_call_repeat1,
  [422] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(26), 1,
      sym_comment,
    ACTIONS(70), 7,
      ts_builtin_sym_end,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [441] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(27), 1,
      sym_comment,
    ACTIONS(72), 7,
      ts_builtin_sym_end,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym__decimal_literal,
      sym_name,
  [460] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(76), 1,
      anon_sym_CR,
    ACTIONS(79), 1,
      anon_sym_LF,
    STATE(8), 1,
      aux_sym__newline,
    ACTIONS(74), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(28), 2,
      sym_comment,
      aux_sym__statements_repeat1,
  [484] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_CR,
    ACTIONS(11), 1,
      anon_sym_LF,
    STATE(3), 1,
      aux_sym__newline,
    STATE(28), 1,
      aux_sym__statements_repeat1,
    STATE(29), 1,
      sym_comment,
    ACTIONS(25), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [510] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_CR,
    ACTIONS(11), 1,
      anon_sym_LF,
    STATE(5), 1,
      aux_sym__newline,
    STATE(29), 1,
      aux_sym__statements_repeat1,
    STATE(30), 1,
      sym_comment,
    ACTIONS(82), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [536] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_CR,
    ACTIONS(11), 1,
      anon_sym_LF,
    ACTIONS(60), 1,
      anon_sym_LPAREN,
    STATE(31), 1,
      sym_comment,
    STATE(36), 1,
      aux_sym__newline,
    ACTIONS(84), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [562] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_CR,
    ACTIONS(11), 1,
      anon_sym_LF,
    ACTIONS(60), 1,
      anon_sym_LPAREN,
    STATE(32), 1,
      sym_comment,
    STATE(38), 1,
      aux_sym__newline,
    ACTIONS(86), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [588] = 9,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_CR,
    ACTIONS(11), 1,
      anon_sym_LF,
    ACTIONS(62), 1,
      anon_sym_COMMA,
    ACTIONS(88), 1,
      anon_sym_RPAREN,
    STATE(9), 1,
      aux_sym__newline,
    STATE(33), 1,
      sym_comment,
    STATE(48), 1,
      aux_sym_function_call_repeat1,
  [616] = 9,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_CR,
    ACTIONS(11), 1,
      anon_sym_LF,
    ACTIONS(62), 1,
      anon_sym_COMMA,
    ACTIONS(64), 1,
      anon_sym_RPAREN,
    STATE(9), 1,
      aux_sym__newline,
    STATE(34), 1,
      sym_comment,
    STATE(45), 1,
      aux_sym_function_call_repeat1,
  [644] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(35), 1,
      sym_comment,
    ACTIONS(90), 5,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [661] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_CR,
    ACTIONS(11), 1,
      anon_sym_LF,
    STATE(9), 1,
      aux_sym__newline,
    STATE(36), 1,
      sym_comment,
    ACTIONS(92), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [684] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(96), 1,
      anon_sym_LPAREN,
    STATE(37), 1,
      sym_comment,
    ACTIONS(94), 4,
      ts_builtin_sym_end,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_RBRACE,
  [703] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_CR,
    ACTIONS(11), 1,
      anon_sym_LF,
    STATE(9), 1,
      aux_sym__newline,
    STATE(38), 1,
      sym_comment,
    ACTIONS(84), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [726] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(39), 1,
      sym_comment,
    ACTIONS(96), 5,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [743] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(40), 1,
      sym_comment,
    ACTIONS(74), 4,
      ts_builtin_sym_end,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_RBRACE,
  [759] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(41), 1,
      sym_comment,
    ACTIONS(29), 4,
      ts_builtin_sym_end,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_RBRACE,
  [775] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(42), 1,
      sym_comment,
    ACTIONS(98), 4,
      ts_builtin_sym_end,
      anon_sym_CR,
      anon_sym_LF,
      anon_sym_RBRACE,
  [791] = 6,
    ACTIONS(100), 1,
      aux_sym_comment_token1,
    ACTIONS(102), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(104), 1,
      aux_sym_comment_token2,
    ACTIONS(106), 1,
      anon_sym_STAR_SLASH,
    STATE(43), 1,
      sym_comment,
    STATE(49), 1,
      aux_sym_comment_repeat1,
  [810] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(62), 1,
      anon_sym_COMMA,
    ACTIONS(64), 1,
      anon_sym_RPAREN,
    STATE(44), 1,
      sym_comment,
    STATE(47), 1,
      aux_sym_function_call_repeat1,
  [829] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(62), 1,
      anon_sym_COMMA,
    ACTIONS(88), 1,
      anon_sym_RPAREN,
    STATE(45), 1,
      sym_comment,
    STATE(47), 1,
      aux_sym_function_call_repeat1,
  [848] = 6,
    ACTIONS(100), 1,
      aux_sym_comment_token1,
    ACTIONS(102), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(104), 1,
      aux_sym_comment_token2,
    ACTIONS(108), 1,
      anon_sym_STAR_SLASH,
    STATE(43), 1,
      aux_sym_comment_repeat1,
    STATE(46), 1,
      sym_comment,
  [867] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(86), 1,
      anon_sym_RPAREN,
    ACTIONS(110), 1,
      anon_sym_COMMA,
    STATE(47), 2,
      sym_comment,
      aux_sym_function_call_repeat1,
  [884] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(62), 1,
      anon_sym_COMMA,
    ACTIONS(113), 1,
      anon_sym_RPAREN,
    STATE(47), 1,
      aux_sym_function_call_repeat1,
    STATE(48), 1,
      sym_comment,
  [903] = 5,
    ACTIONS(100), 1,
      aux_sym_comment_token1,
    ACTIONS(102), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(115), 1,
      aux_sym_comment_token2,
    ACTIONS(118), 1,
      anon_sym_STAR_SLASH,
    STATE(49), 2,
      sym_comment,
      aux_sym_comment_repeat1,
  [920] = 4,
    ACTIONS(100), 1,
      aux_sym_comment_token1,
    ACTIONS(102), 1,
      anon_sym_SLASH_STAR,
    STATE(50), 1,
      sym_comment,
    ACTIONS(120), 2,
      aux_sym_comment_token2,
      anon_sym_STAR_SLASH,
  [934] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(60), 1,
      anon_sym_LPAREN,
    STATE(51), 1,
      sym_comment,
  [947] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(122), 1,
      ts_builtin_sym_end,
    STATE(52), 1,
      sym_comment,
  [960] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(124), 1,
      ts_builtin_sym_end,
    STATE(53), 1,
      sym_comment,
  [973] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(27), 1,
      anon_sym_RBRACE,
    STATE(54), 1,
      sym_comment,
  [986] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(126), 1,
      anon_sym_LF,
    STATE(55), 1,
      sym_comment,
  [999] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    STATE(56), 1,
      sym_comment,
  [1012] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(128), 1,
      anon_sym_RBRACE,
    STATE(57), 1,
      sym_comment,
  [1025] = 1,
    ACTIONS(130), 1,
      ts_builtin_sym_end,
  [1029] = 1,
    ACTIONS(132), 1,
      ts_builtin_sym_end,
  [1033] = 1,
    ACTIONS(134), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 26,
  [SMALL_STATE(11)] = 47,
  [SMALL_STATE(12)] = 82,
  [SMALL_STATE(13)] = 107,
  [SMALL_STATE(14)] = 142,
  [SMALL_STATE(15)] = 163,
  [SMALL_STATE(16)] = 195,
  [SMALL_STATE(17)] = 227,
  [SMALL_STATE(18)] = 246,
  [SMALL_STATE(19)] = 265,
  [SMALL_STATE(20)] = 284,
  [SMALL_STATE(21)] = 303,
  [SMALL_STATE(22)] = 322,
  [SMALL_STATE(23)] = 353,
  [SMALL_STATE(24)] = 372,
  [SMALL_STATE(25)] = 391,
  [SMALL_STATE(26)] = 422,
  [SMALL_STATE(27)] = 441,
  [SMALL_STATE(28)] = 460,
  [SMALL_STATE(29)] = 484,
  [SMALL_STATE(30)] = 510,
  [SMALL_STATE(31)] = 536,
  [SMALL_STATE(32)] = 562,
  [SMALL_STATE(33)] = 588,
  [SMALL_STATE(34)] = 616,
  [SMALL_STATE(35)] = 644,
  [SMALL_STATE(36)] = 661,
  [SMALL_STATE(37)] = 684,
  [SMALL_STATE(38)] = 703,
  [SMALL_STATE(39)] = 726,
  [SMALL_STATE(40)] = 743,
  [SMALL_STATE(41)] = 759,
  [SMALL_STATE(42)] = 775,
  [SMALL_STATE(43)] = 791,
  [SMALL_STATE(44)] = 810,
  [SMALL_STATE(45)] = 829,
  [SMALL_STATE(46)] = 848,
  [SMALL_STATE(47)] = 867,
  [SMALL_STATE(48)] = 884,
  [SMALL_STATE(49)] = 903,
  [SMALL_STATE(50)] = 920,
  [SMALL_STATE(51)] = 934,
  [SMALL_STATE(52)] = 947,
  [SMALL_STATE(53)] = 960,
  [SMALL_STATE(54)] = 973,
  [SMALL_STATE(55)] = 986,
  [SMALL_STATE(56)] = 999,
  [SMALL_STATE(57)] = 1012,
  [SMALL_STATE(58)] = 1025,
  [SMALL_STATE(59)] = 1029,
  [SMALL_STATE(60)] = 1033,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statements, 3),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statements, 2),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_line, 1),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__newline, 2),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__newline, 2), SHIFT_REPEAT(55),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__newline, 2), SHIFT_REPEAT(10),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__newline, 1),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__statement_line_repeat1, 2),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__statement_line_repeat1, 2), SHIFT_REPEAT(2),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 7),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 6),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 5),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__statement_line_repeat1, 1),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__statements_repeat1, 2),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__statements_repeat1, 2), SHIFT_REPEAT(55),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__statements_repeat1, 2), SHIFT_REPEAT(10),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statements, 1),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 3),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__numeric_literal, 1),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 4),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 1),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_line, 2),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2), SHIFT_REPEAT(16),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [115] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2), SHIFT_REPEAT(50),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 1),
  [122] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_via(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
